### ISSUE TITLE
Incorrect howto in readme.md

### ISSUE THREAD

**Issue by jaapcrezee** [mlliarm/bird-classifier#1]
Hi,

I am unable to use the instructions as stated in the readme.md:

```
(.pyenv) [jaap@jaap /data3/ml/bird-classifier ]$ python runner.py imgs/bird_01.jpg 
imgs/bird_01.jpg
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
(.pyenv) [jaap@jaap /data3/ml/bird-classifier ]$ python runner.py file://$PWD/imgs/bird_01.jpg 
file:///data3/ml/bird-classifier/imgs/bird_01.jpg
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
Run: 1
Top match: Phalacrocorax varius varius with score: 0.5863155126571655
Top match: Microcarbo melanoleucos with score: 0.1443489044904709
Top match: Phalacrocorax varius with score: 0.13292503356933594


Total time spent: 3.0371804237365723 sec
Average time spent per image was: 3.0371804237365723  sec
(.pyenv) [jaap@jaap /data3/ml/bird-classifier ]$ 

```

I debugged the software and found out `requests` is being used for opening files. Therefore I have to use the file://.. syntax. Could you clarify or update the readme?
Thanks

Jaap

**Comment by mlliarm** [comment]
Hello @jaapcrezee ,

Thanks for the bug report, I'll check it right away !

Best,
Michail

**Comment by mlliarm** [comment]
Jaap, you're totally right, reproduced the issue (on Windows 10) with a python 3.9.

It works with either the two following cases:

`python runner.py file://$PWD/imgs/bird_01.jpg`

or

`python runner.py 'https://i.imgur.com/8eGMhGP.jpg'`

Thanks for reporting this.

**Comment by mlliarm** [comment]
Fixed, closing

**Comment by jaapcrezee** [comment]
(Y)
